name: build
on:
  push:
    branches:
      - main
jobs:
  all-in-one:
    name: Aqua scanner
    runs-on: ubuntu-latest
    environment: main
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: "stanhoe"
      DOCKER_REPOSITORY: "demo-vuln-genai"
      IMAGE_TAG: ${{ github.sha }}
      AQUA_KEY: ${{ secrets.AQUA_KEY }}
      AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
      TRIVY_RUN_AS_PLUGIN: 'aqua'
      GITHUB_TOKEN: ${{ github.token }}
      AQUA_URL: https://api.asia-1.supply-chain.cloud.aquasec.com
      CSPM_URL: https://asia-1.api.cloudsploit.com
      BUILD_NUMBER: ${{ github.run_id }}
      BUILD_NAME: ${{ github.repository }}
      AQUA_TOKEN: ${{ secrets.AQUA_TOKEN }} # Aqua Scanner authentication
      AQUA_HOST: ${{ secrets.AQUA_HOST }} # Aqua Scanner authentication
      AQUA_USER: ${{ secrets.AQUA_USER }} # Aqua Registry
      AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }} # Aqua Registry
      
    permissions:
        id-token: write
    
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 32768 # The Go cache (`~/.cache/go-build` and `~/go/pkg`) requires a lot of storage space.
          remove-android: 'true'
          remove-docker-images: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Aqua Code Scanner
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy -d fs --scanners config,vuln,secret . --sast --reachability
          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          # To enable SAST scanning, add: --sast
          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj  
      - name: Build image locally
        run: |
          docker build -t "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" .
      # - name: Login to Aqua Registry
      #   uses: docker/login-action@v3
      #   with:
      #     username: $AQUA_USER
      #     password: $AQUA_PASSWORD
      #     registry: registry.aquasec.com 
      - name: Run Aqua Image Scanner
        run: |
          docker login -u $AQUA_USER -p $AQUA_PASSWORD
          docker pull registry.aquasec.com/scanner:2404.30.6 
          docker run --rm -v $GITHUB_WORKSPACE:/tmp -v /var/run/docker.sock:/var/run/docker.sock -e BUILD_NUMBER=$BUILD_NUMBER -e BUILD_JOB_NAME=$BUILD_NAME registry.aquasec.com/scanner:2404.30.6 scan -w /tmp --host $AQUA_HOST --token $AQUA_TOKEN --show-negligible --local $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG --htmlfile /tmp/out.html --jsonfile /tmp/out.json > /dev/null
      - name: Manifest Generation
        run: |
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | shasum -a 256 ; then
            echo "install.sh checksum failed"
            exit 1
          fi
          sh install.sh
          rm install.sh install.sh.checksum
          billy generate \
              --access-token "${{ secrets.GITHUB_TOKEN }}" \
              --aqua-key "${{ secrets.AQUA_KEY }}" \
              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
              --artifact-path "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
      - name: Tag and push image to Docker Hub (+latest)
        run: |
          docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
